/*
 * Copyright (C) 2016 Lamar J. Smith
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.event.ListSelectionListener;
import model.BusLine;
import model.BusLine.Direction;
import model.BusLine.Stop;
import model.RouteStop;

/**
 *
 * @author Lamar
 */
public class AddRouteUI extends javax.swing.JDialog {

    /**
     * Creates new form RouteDialog
     *
     * @param parent
     * @param modal
     */
    public AddRouteUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRouteName = new javax.swing.JLabel();
        txtFieldRouteName = new javax.swing.JTextField();
        srlPanStopsAdded = new javax.swing.JScrollPane();
        lstStopsAdded = new javax.swing.JList<>();
        lblStopsAdded = new javax.swing.JLabel();
        btnSaveRoute = new javax.swing.JButton();
        pnlAddStop = new javax.swing.JPanel();
        lblAddStop = new javax.swing.JLabel();
        tabPanAddStop = new javax.swing.JTabbedPane();
        pnlAddStopsBus = new javax.swing.JPanel();
        cmbBusSelector = new javax.swing.JComboBox<>();
        lblBusSelector = new javax.swing.JLabel();
        btnBusAddStop = new javax.swing.JButton();
        cmbBusDirectionSelector = new javax.swing.JComboBox<>();
        lblBusDirectionSelector = new javax.swing.JLabel();
        lblStopSelector = new javax.swing.JLabel();
        cmbStopSelector = new javax.swing.JComboBox<>();
        pnlAddStopTrain = new javax.swing.JPanel();
        lblTrainSelector = new javax.swing.JLabel();
        cmbTrainSelector = new javax.swing.JComboBox<>();
        lblStationSelector = new javax.swing.JLabel();
        cmbStationSelector = new javax.swing.JComboBox<>();
        lblTrainDirectionSelector = new javax.swing.JLabel();
        cmbTrainDirectionSelector = new javax.swing.JComboBox<>();
        btnTrainAddStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        lblRouteName.setText("Route Name");

        lstStopsAdded.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        srlPanStopsAdded.setViewportView(lstStopsAdded);

        lblStopsAdded.setText("Stops Added To Route");

        btnSaveRoute.setText("Save Route");

        lblAddStop.setText("Add buses and trains to the new route.");

        lblBusSelector.setText("Bus Name/Number");

        btnBusAddStop.setText("Add Bus Stop To Route");

        lblBusDirectionSelector.setText("Direction");

        lblStopSelector.setText("Stop");

        javax.swing.GroupLayout pnlAddStopsBusLayout = new javax.swing.GroupLayout(pnlAddStopsBus);
        pnlAddStopsBus.setLayout(pnlAddStopsBusLayout);
        pnlAddStopsBusLayout.setHorizontalGroup(
            pnlAddStopsBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddStopsBusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddStopsBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBusSelector)
                    .addComponent(cmbBusSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBusDirectionSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBusDirectionSelector)
                    .addComponent(lblStopSelector)
                    .addComponent(cmbStopSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddStopsBusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBusAddStop, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlAddStopsBusLayout.setVerticalGroup(
            pnlAddStopsBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddStopsBusLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblBusSelector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbBusSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBusDirectionSelector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbBusDirectionSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStopSelector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbStopSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBusAddStop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabPanAddStop.addTab("Bus", pnlAddStopsBus);

        lblTrainSelector.setText("Train Name");

        lblStationSelector.setText("Station");

        lblTrainDirectionSelector.setText("Direction");

        btnTrainAddStop.setText("Add Train Stop To Route");

        javax.swing.GroupLayout pnlAddStopTrainLayout = new javax.swing.GroupLayout(pnlAddStopTrain);
        pnlAddStopTrain.setLayout(pnlAddStopTrainLayout);
        pnlAddStopTrainLayout.setHorizontalGroup(
            pnlAddStopTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddStopTrainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddStopTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTrainSelector)
                    .addComponent(cmbTrainSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbStationSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStationSelector)
                    .addComponent(lblTrainDirectionSelector)
                    .addComponent(cmbTrainDirectionSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddStopTrainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTrainAddStop, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlAddStopTrainLayout.setVerticalGroup(
            pnlAddStopTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddStopTrainLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblTrainSelector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTrainSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStationSelector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbStationSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrainDirectionSelector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTrainDirectionSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrainAddStop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabPanAddStop.addTab("Train", pnlAddStopTrain);

        javax.swing.GroupLayout pnlAddStopLayout = new javax.swing.GroupLayout(pnlAddStop);
        pnlAddStop.setLayout(pnlAddStopLayout);
        pnlAddStopLayout.setHorizontalGroup(
            pnlAddStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddStopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPanAddStop, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddStop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAddStopLayout.setVerticalGroup(
            pnlAddStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddStopLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblAddStop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanAddStop, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRouteName)
                    .addComponent(txtFieldRouteName)
                    .addComponent(pnlAddStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSaveRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStopsAdded)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(srlPanStopsAdded, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRouteName)
                    .addComponent(lblStopsAdded))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(srlPanStopsAdded)
                        .addGap(12, 12, 12)
                        .addComponent(btnSaveRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFieldRouteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlAddStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusAddStop;
    private javax.swing.JButton btnSaveRoute;
    private javax.swing.JButton btnTrainAddStop;
    private javax.swing.JComboBox<Direction> cmbBusDirectionSelector;
    private javax.swing.JComboBox<BusLine> cmbBusSelector;
    private javax.swing.JComboBox<String> cmbStationSelector;
    private javax.swing.JComboBox<Stop> cmbStopSelector;
    private javax.swing.JComboBox<String> cmbTrainDirectionSelector;
    private javax.swing.JComboBox<String> cmbTrainSelector;
    private javax.swing.JLabel lblAddStop;
    private javax.swing.JLabel lblBusDirectionSelector;
    private javax.swing.JLabel lblBusSelector;
    private javax.swing.JLabel lblRouteName;
    private javax.swing.JLabel lblStationSelector;
    private javax.swing.JLabel lblStopSelector;
    private javax.swing.JLabel lblStopsAdded;
    private javax.swing.JLabel lblTrainDirectionSelector;
    private javax.swing.JLabel lblTrainSelector;
    private javax.swing.JList<RouteStop> lstStopsAdded;
    private javax.swing.JPanel pnlAddStop;
    private javax.swing.JPanel pnlAddStopTrain;
    private javax.swing.JPanel pnlAddStopsBus;
    private javax.swing.JScrollPane srlPanStopsAdded;
    private javax.swing.JTabbedPane tabPanAddStop;
    private javax.swing.JTextField txtFieldRouteName;
    // End of variables declaration//GEN-END:variables

    /**
     * @param listener
     */
    public void addBtnBusAddStopListener(ActionListener listener) {
        btnBusAddStop.addActionListener(listener);
    }

    /**
     * @param listener
     */
    public void addBtnSaveRouteListener(ActionListener listener) {
        btnSaveRoute.addActionListener(listener);
    }

    /**
     * @param listener
     */
    public void addBtnTrainAddStopListener(ActionListener listener) {
        btnTrainAddStop.addActionListener(listener);
    }

    /**
     * @param listener
     */
    public void addCmbBusDirectionSelectorListener(ItemListener listener) {
        cmbBusDirectionSelector.addItemListener(listener);
    }

    /**
     * @param listener
     */
    public void addCmbBusSelectorListener(ItemListener listener) {
        cmbBusSelector.addItemListener(listener);
    }

    /**
     * @param listener
     */
    public void addCmbStationSelectorListener(ItemListener listener) {
        cmbStationSelector.addItemListener(listener);
    }

    /**
     * @param listener
     */
    public void addCmbStopSelectorListener(ItemListener listener) {
        cmbStopSelector.addItemListener(listener);
    }

    /**
     * @param listener
     */
    public void addCmbTrainDirectionSelectorListener(ItemListener listener) {
        cmbTrainDirectionSelector.addItemListener(listener);
    }

    /**
     * @param listener
     */
    public void addCmbTrainSelectorListener(ItemListener listener) {
        cmbTrainSelector.addItemListener(listener);
    }

    /**
     * @param listener
     */
    public void addLstStopsAddedListener(ListSelectionListener listener) {
        lstStopsAdded.addListSelectionListener(listener);
    }

    /**
     * @param listener
     */
    public void addTxtFieldRouteNameListener(ActionListener listener) {
        txtFieldRouteName.addActionListener(listener);
    }    

    /**
     * @return the btnBusAddStop
     */
    public javax.swing.JButton getBtnBusAddStop() {
        return btnBusAddStop;
    }

    /**
     * @return the btnSaveRoute
     */
    public javax.swing.JButton getBtnSaveRoute() {
        return btnSaveRoute;
    }

    /**
     * @return the btnTrainAddStop
     */
    public javax.swing.JButton getBtnTrainAddStop() {
        return btnTrainAddStop;
    }

    /**
     * @return the cmbBusDirectionSelector
     */
    public JComboBox<Direction> getCmbBusDirectionSelector() {
        return cmbBusDirectionSelector;
    }

    /**
     * @return the cmbBusSelector
     */
    public JComboBox<BusLine> getCmbBusSelector() {
        return cmbBusSelector;
    }

    /**
     * @return the cmbStationSelector
     */
    public JComboBox<String> getCmbStationSelector() {
        return cmbStationSelector;
    }

    /**
     * @return the cmbStopSelector
     */
    public JComboBox<Stop> getCmbStopSelector() {
        return cmbStopSelector;
    }

    /**
     * @return the cmbTrainDirectionSelector
     */
    public JComboBox<String> getCmbTrainDirectionSelector() {
        return cmbTrainDirectionSelector;
    }

    /**
     * @return the cmbTrainSelector
     */
    public JComboBox<String> getCmbTrainSelector() {
        return cmbTrainSelector;
    }

    /**
     * @return the lstStopsAdded
     */
    public JList<RouteStop> getLstStopsAdded() {
        return lstStopsAdded;
    }

    /**
     * @return the txtFieldRouteName
     */
    public javax.swing.JTextField getTxtFieldRouteName() {
        return txtFieldRouteName;
    }
}
